### ISSUE TITLE
Too many call `on_retry`

### ISSUE THREAD

**Issue by yamotonalds** [kamui/retriable#22]
``` rb
Retriable.retriable(tries: 3, on_retry: ->(*args) { puts 'on_retry' }) do
  puts 'execute'
  raise 'err'
end
```

version 1.4.1

```
execute
on_retry
execute
on_retry
execute
RuntimeError: err
```

version 2.1.0

```
execute
on_retry
execute
on_retry
execute
on_retry
RuntimeError: err
```

**Comment by kamui** [comment]
Hmm... when I think about this, I think that version 2.1.0 is doing the correct thing here. `on_retry` gets called after each failed attempt. It makes 3 retries, it should call 3 `on_retry` callbacks.

If the 3rd try had succeeded, then it shouldn't call `on_retry` the 3rd time, because the try didn't fail or raise an exception.

Let me know if you think version 1.4.1 is doing the right thing and why though. I'm open to being wrong on this.
